# Generated by Django 5.1.7 on 2025-04-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Userss',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
    ]
